apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudl-client
    spec:
      containers:
        - name: cloudl-client
          image: kavinduchamiran/cloudl-client:latest
          ports:
            - containerPort: 80
              name: http-port
          env:
            - name: CLOUDL_SERVER
              value: cloudl-server-service
  selector:
    matchLabels:
      app: cloudl-client

